### PR TITLE
azure pipelines [skip travis]

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
CI actually passed, but did not report for some reason :man_shrugging:

**Comment by merwok** [comment]
Maybe some integration is needed (I mean pushing buttons in Azure dashboard)?
There are no status checks for latest commits on master.

**Comment by asottile** [comment]
that's really weird, yeah I'll try poking it again :thinking:  -- worst case I disable and re-enable that usually makes it work

**Comment by asottile** [comment]
ok I think I fixed it?  found a checkbox that was different between my old pipelines and my new ones and that seems to have fixed it!

**Pull request merged**
