### PR TITLE
replace blank key with * in exclude_package_data

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by asottile** [comment]
can you show what this is fixing? I'm not sure what is motivating this patch

**Comment by graingert** [comment]
@asottile setup-py-upgrade produced an invalid `setup.cfg` from this setup.py line: https://github.com/twisted/twisted/pull/1428/files#diff-5b86c09b7a81349feeb7be7946258eddR83

**Comment by asottile** [comment]
can you add a testcase demonstrating?

**Comment by graingert** [comment]
```
 graingert@onomastic  ~/projects/twisted   move-more-content-into-static-package-metadata ± cat setup.py 
from setuptools import setup

setup(
    name="example",
    exclude_package_data={
        "": ["*.c", "*.h", "*.pxi", "*.pyx", "build.bat"],
    }
)
$ pipx run setup-py-upgrade .
./setup.py and ./setup.cfg written!
$ cat setup.cfg 
[metadata]
name = example

[options.exclude_package_data]
 =
    *.c
    *.h
    *.pxi
    *.pyx
    build.bat
$ python setup.py bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    setup()
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 143, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 136, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 699, in parse_config_files
    self._parse_config_files(filenames=filenames)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 596, in _parse_config_files
    (parser.readfp if six.PY2 else parser.read_file)(reader)
  File "/usr/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/lib/python3.8/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: 'setup.cfg'
	[line  5]: ' =\n'
	[line  6]: '    *.c\n'
	[line  7]: '    *.h\n'
	[line  8]: '    *.pxi\n'
	[line  9]: '    *.pyx\n'
	[line 10]: '    build.bat\n'
```

**Comment by graingert** [comment]
sure

**Pull request merged**
